### ISSUE TITLE
`natefoo.postgresql_objects` HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by martinwolst** [galaxyproject/ansible-postgresql-objects#10]
With: ansible [core 2.11.12]

The role fails to install for me, has worked in the past so I'm guessing a recent change.

```
ansible-galaxy install -p roles natefoo.postgresql_objects
Starting galaxy role install process
- downloading role 'postgresql_objects', owned by natefoo
- downloading role from https://github.com/natefoo/ansible-postgresql-objects/archive/1.1.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - natefoo.postgresql_objects was NOT installed successfully.
```

**Comment by hexylena** [comment]
Hi, it's renamed, as you can tell by this project's github page. Please replace `natefoo` to `galaxyproject`.

**Comment by martinwolst** [comment]
Of course, thank you! I was confused because the ansible galaxy page for the old role name redirected me to the new github

**Comment by hexylena** [comment]
Yeah, it's not great that galaxy.ansible.com doesn't redirect renamed roles.
