### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.postgresql.postgresql_privs'.

### ISSUE THREAD

**Issue by Tronde** [galaxyproject/ansible-postgresql-objects#12]
Hello Team,  
Using your role as part of my playbook I get the following error:

~~~
ERROR! couldn't resolve module/action 'community.postgresql.postgresql_privs'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/…/ansible/roles/galaxyproject.postgresql_objects/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Revoke extra privileges
  ^ here
~~~

Looking at the line in question I see that `community.postgresql.postgresql_privs` is used there. But I cannot find `community.postgresql.postgresql_privs` or `community.posgresql` on Galaxy.

Am i holding it wrong? Or is there something broken in this role?

I would appreciate if you find the time to look into it and respond to this issue with information whether this is a usage issue or some kind of bug.

Best regards,  
Tronde

**Comment by Tronde** [comment]
Sorry, I did hold it wrong.

Somehow I missed that this is a collection and not a role, so `ansible-galaxy search community.postgresql` didn't find it but `ansible-galaxy collection list community.postgresql` did.

Sorry for open this issue uneccessarily.

**Comment by bgruening** [comment]
Glad you could figure it out. Let us know if you have any other problem.
